#!/usr/bin/env python3
"""Verify V550 canonical hashes, generated bytes, and destination declarations."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from canonical_course_materials import InstructorMaterialError, load_precedent_cards
from sync_runtime_knowledge import (
    DEFAULT_MANIFEST,
    ManifestError,
    load_manifest,
    repo_root,
    safe_repo_path,
    validate_declarations,
)


def issue(errors: list[dict[str, str]], code: str, path: str, message: str) -> None:
    errors.append({"code": code, "path": path, "message": message})


def verify(root: Path, manifest_path: Path = DEFAULT_MANIFEST) -> dict[str, Any]:
    errors: list[dict[str, str]] = []
    try:
        manifest, resolved_manifest = load_manifest(root, manifest_path)
        declarations = validate_declarations(root, manifest)
    except (ManifestError, OSError) as exc:
        return {"valid": False, "errorCount": 1, "errors": [{"code": "MANIFEST", "path": "$", "message": str(exc)}]}

    declared: set[Path] = set()
    checks: list[dict[str, Any]] = []
    comparison_example_count = 0
    for declaration in declarations:
        source: Path = declaration["source"]
        if source.name == "gate-1-precedent-cards.md":
            try:
                comparison_example_count = len(load_precedent_cards(source))
            except InstructorMaterialError as exc:
                issue(
                    errors,
                    "INSTRUCTOR_MATERIAL_NEEDED",
                    source.relative_to(root).as_posix(),
                    str(exc),
                )
        source_data = source.read_bytes()
        actual_hash = hashlib.sha256(source_data).hexdigest()
        expected_hash = declaration["item"].get("sha256")
        source_label = source.relative_to(root).as_posix()
        if not isinstance(expected_hash, str) or expected_hash != actual_hash:
            issue(errors, "SOURCE_HASH_MISMATCH", source_label, "Canonical source digest does not match the manifest.")
        for destination in declaration["destinations"]:
            declared.add(destination)
            label = destination.relative_to(root).as_posix()
            if not destination.is_file():
                issue(errors, "DESTINATION_MISSING", label, "Declared generated destination is missing.")
                checks.append({"source": source_label, "destination": label, "equal": False})
                continue
            equal = destination.read_bytes() == source_data
            checks.append({"source": source_label, "destination": label, "equal": equal})
            if not equal:
                issue(errors, "DESTINATION_DRIFT", label, "Generated destination differs byte-for-byte from its canonical source.")

    for root_value in manifest["protected_generated_roots"]:
        protected = safe_repo_path(root, root_value, "protected_generated_root")
        if not protected.exists():
            issue(errors, "GENERATED_ROOT_MISSING", protected.relative_to(root).as_posix(), "Protected generated root is missing.")
            continue
        for candidate in sorted(path for path in protected.rglob("*") if path.is_file()):
            if candidate not in declared:
                issue(errors, "UNDECLARED_DESTINATION", candidate.relative_to(root).as_posix(), "Generated file has no canonical source declaration.")

    return {
        "valid": not errors,
        "manifest": resolved_manifest.relative_to(root).as_posix(),
        "canonicalSourceCount": len(declarations),
        "destinationCount": len(checks),
        "comparisonExampleCount": comparison_example_count,
        "checks": checks,
        "errorCount": len(errors),
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo_root", nargs="?", type=Path, help="Optional repository root")
    parser.add_argument("--repo-root", dest="repo_root_option", type=Path, help="Repository root")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--pretty", action="store_true")
    args = parser.parse_args()
    root = (args.repo_root_option or args.repo_root or repo_root()).resolve()
    result = verify(root, args.manifest)
    print(json.dumps(result, indent=2 if args.pretty else None, ensure_ascii=False))
    return 0 if result["valid"] else 1


if __name__ == "__main__":
    sys.exit(main())
